version: '3'

services:
  mongo:
    build: ./docker/mongo
    ports:
      - 27017:27017
    command: [--auth]
    environment:
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pwd
      - MONGO_INITDB_DATABASE=cronpad
    #volumes:
    #  - ./docker/mongo/db:/data/db

  keycloak:
    build: ./docker/keycloak
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      # - KEYCLOAK_LOGLEVEL=DEBUG

  cronpad:
    build: .
    ports:
      - 4000:4000
      - 9000:9000
    environment:
      - CRONPAD_URL=http://<host-address>:9000
      - KEYCLOAK_URL=http://<host-address>:8080
      - MONGO_HOST=mongo
      - MONGO_USER=user
      - MONGO_PASSWORD=pwd
    depends_on:
      - mongo
      - keycloak