version: '3'

services:
  mongo:
    build: ./docker/mongo
    # image: docker.pkg.github.com/ts-dmitry/cronpad/mongo:latest
    command: [--auth]
    environment:
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pwd
      - MONGO_INITDB_DATABASE=cronpad
    #volumes:
    #  - ./docker/mongo/db:/data/db

  keycloak:
    build: ./docker/keycloak
    # image: docker.pkg.github.com/ts-dmitry/cronpad/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      # - KEYCLOAK_LOGLEVEL=DEBUG

  cronpad:
    build: .
    # image: docker.pkg.github.com/ts-dmitry/cronpad/proxy:latest
    environment:
      - CRONPAD_URL=http://<host-address>
      - KEYCLOAK_URL=http://<host-address>
      - MONGO_HOST=mongo
      - MONGO_USER=user
      - MONGO_PASSWORD=pwd
    depends_on:
      - mongo
      - keycloak

  proxy:
    build: ./docker/reverse-proxy
    # image: docker.pkg.github.com/ts-dmitry/cronpad/proxy:latest
    ports:
      - 80:80
    depends_on:
      - cronpad
      - keycloak