version: '3'

services:
  cronpad:
    image: docker.pkg.github.com/ts-dmitry/cronpad/cronpad:latest
    environment:
      - CRONPAD_URL=<host-address>
      - KEYCLOAK_URL=<host-address>
      - MONGO_HOST=mongo
      - MONGO_USER=user
      - MONGO_PASSWORD=pwd
    depends_on:
      - mongo
      - keycloak

  mongo:
    image: docker.pkg.github.com/ts-dmitry/cronpad/mongo:latest
    command: [--auth]
    environment:
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pwd
      - MONGO_INITDB_DATABASE=cronpad

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  
  proxy:
    image: docker.pkg.github.com/ts-dmitry/cronpad/proxy:latest
    ports:
      - 80:80
    depends_on:
      - cronpad
      - keycloak
    